development:
  adapter: postgresql
  encoding: unicode
  database: wsmdb
  host: localhost
  pool: 5
  username: wsm
  password: password

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: wsmdb
  host: localhost
  pool: 50
  username: wsm
  password: password
